# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:
  # see https://www.appveyor.com/docs/build-environment/#python
  matrix:
    # cvxopt is only available for python <3.5
    # https://github.com/cvxopt/cvxopt/issues/94
    - TARGET_ARCH: "x64"
      CONDA_PY: "35"
      PY_CONDITION: "python=3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "36"
      PY_CONDITION: "python=3.6"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "37"
      PY_CONDITION: "python=3.7"
      CONDA_INSTALL_LOCN: "C:\\Miniconda37-x64"

# We always use a 64-bit machine.
platform:
- x64

install:
  - cmd: set "OLDPATH=%PATH%"
  - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
  - cmd: move /Y ci\appveyor\condarc C:\Users\appveyor\.condarc
  - cmd: conda update --yes --quiet conda
  - cmd: set "PATH=%OLDPATH%"
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda info -a

  # Install the build and runtime dependencies of the project.
  - cmd: conda create -n sksurv-test "%PY_CONDITION%"
  - cmd: conda install -n sksurv-test -c conda-forge "blas=*=openblas" --file ci\appveyor\requirements_%CONDA_PY%.yaml
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat sksurv-test
  # Install cvxpy via pip
  - cmd: pip install --no-cache-dir "cvxpy>=1.0"
  - cmd: conda list
  # Initialize the submodules
  - cmd: git submodule update --init --recursive
  # Create binary packages for the project.
  - cmd: python setup.py bdist_wheel bdist_wininst
  - ps: "ls dist"

  # Install the generated wheel package to test it
  - cmd: pip install --exists-action=w --pre --no-index --find-links dist/ scikit-survival
  - cmd: rmdir sksurv /s /q

test_script:
  - cmd: set "PYTHONWARNINGS=default"
  - cmd: py.test -m "not slow" -k "not test_breast_cancer_rbf_cvxopt" tests/

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

# Skip .NET project specific build phase.
build: off
