name: sksurv-test
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - cython>=0.29
  - cvxopt>=1.1.9
  - numexpr
  - numpy=1.14
  - pytest
  - pytest-cov
  - scipy
  - scikit-learn<0.21
  - pandas=0.22
  - blas=*=openblas